### ISSUE TITLE
实验室协作者创建

### ISSUE THREAD

**Issue by YLZylkj** [Crane-lin/july#19]
<p><br></p><pre><code class="language-typescript">public class Test1 {
   public static void main(String args[]) {
      int x = 10;
      while( x &lt; 20 ) {
          System.out.print("value of x : " + x );
          x++;
          System.out.print("\n");
      }
   } 
} </code></pre><p><br></p>

**Comment by YLZylkj** [comment]
<p>是有什么问题嘛~</p>

**Comment by Crane-lin** [comment]
<p>test10086</p>

**Comment by Crane-lin** [comment]
超管在GitHub回复
